In [1]:
# %pip install scikit-learn pandas

In [2]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(random_state=0)

# 2 samples, 3 features
X = [[ 1,  2,  3],
     [11, 12, 13]]

# labels
y = [0, 1]

# train model
clf.fit(X, y)

# unseen data
Z = [[ 4,  5,  6], 
     [14, 15, 16]]

# make a prediction
clf.predict(Z)

array([0, 1])

In [3]:
from sklearn.preprocessing import Binarizer
X = [[0.5, 5.0, 0.2],
     [0.1, 1.0, 0.3],
     [0.7, 0.2, 0.4],
     [0.4, 3.0, 0.3]]

# binarize the matrix
Binarizer(threshold=0.3).fit_transform(X)

array([[1., 1., 0.],
       [0., 1., 0.],
       [1., 0., 1.],
       [1., 1., 0.]])

In [4]:
from sklearn.datasets import make_regression
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [5]:
from sklearn.datasets import make_regression
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# generate dummy regression data
X, y = make_regression(n_samples=1000, random_state=0)

# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0) # tirar duvida de convenção de tam. de test case

# transform training set
X_train_scaled = StandardScaler().fit_transform(X_train)

# create and train a model
lr = LinearRegression()
lr.fit(X_train_scaled, y_train)

# transform testing set
X_test_scaled = StandardScaler().fit_transform(X_test) # tirar duvida do que isso faz -> devolve (x - media) / dp
pred = lr.predict(X_test_scaled)

# evaluate the model
mean_squared_error(pred, y_test)

250.1489545656354

In [6]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# create a pipeline object
pipe = make_pipeline( # evita ter que passar por cada etapa pra cada bloco de dados (economiza linha kk)
    StandardScaler(),
    LogisticRegression()
)

# load the iris dataset and split it into train and test sets
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

# fit the whole pipeline
pipe.fit(X_train, y_train)

# we can now use it like any other estimator
accuracy_score(pipe.predict(X_test), y_test)
# mean_squared_error(pipe.predict(X_test), y_test)

0.9736842105263158

# Mushroom Dataset

In [7]:
import pandas as pd

In [ ]:
shrooms_df = pd.read_csv('../../data/mushrooms.csv')

In [9]:
shrooms_df.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [10]:
shrooms_df.shape

(8124, 23)

In [11]:
shrooms_df['class'].value_counts()

class
e    4208
p    3916
Name: count, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import CategoricalNB, GaussianNB
from sklearn.metrics import classification_report, confusion_matrix, precision_recall_curve, auc, roc_curve, roc_auc_score, accuracy_score

In [13]:
shrooms_df = shrooms_df.apply(LabelEncoder().fit_transform)

In [14]:
shrooms_df.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,1,5,2,4,1,6,1,0,1,4,...,2,7,7,0,2,1,4,2,3,5
1,0,5,2,9,1,0,1,0,0,4,...,2,7,7,0,2,1,4,3,2,1
2,0,0,2,8,1,3,1,0,0,5,...,2,7,7,0,2,1,4,3,2,3
3,1,5,3,8,1,6,1,0,1,5,...,2,7,7,0,2,1,4,2,3,5
4,0,5,2,3,0,5,1,1,0,4,...,2,7,7,0,2,1,0,3,0,1

In [15]:
shrooms_df.sum()

class                        3916
cap-shape                   27200
cap-surface                 14848
cap-color                   36596
bruises                      3376
odor                        33672
gill-attachment              7914
gill-spacing                 1312
gill-size                    2512
gill-color                  39082
stalk-shape                  4608
stalk-root                   9016
stalk-surface-above-ring    12796
stalk-surface-below-ring    13028
stalk-color-above-ring      47252
stalk-color-below-ring      47076
veil-type                       0
veil-color                  15968
ring-number                  8688
ring-type                   18620
spore-print-color           29220
population                  29604
habitat                     12256
dtype: int64

column 'veil-type' is all 0s, let's remove it

In [16]:
shrooms_df = shrooms_df.drop(['veil-type'], axis=1)

In [17]:
shrooms_df.shape

(8124, 22)

## Split the dataset

In [18]:
X = shrooms_df.drop(['class'], axis=1)
y = shrooms_df['class']
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=13, test_size=0.2)

In [19]:
X_train.shape

(6499, 21)

In [20]:
X_test.shape

(1625, 21)

In [21]:
cnb_clf = CategoricalNB().fit(X_train, y_train)

In [22]:
lr_clf = LogisticRegression(max_iter=600).fit(X_train, y_train)

In [23]:
accuracy_score(cnb_clf.predict(X_test), y_test)

0.9513846153846154

In [24]:
accuracy_score(lr_clf.predict(X_test), y_test)

0.9526153846153846